
export const HOME_ROUTE = '/home'
export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const SIGN_ROUTE = '/sign'
export const PROPERTIES_ROUTE = '/properties'
export const BLOG_ROUTE = '/blog'
export const ABOUT_ROUTE = '/about'
export const SERVICES_ROUTE = '/services'
export const COMPANIES_ROUTE = '/companies'
export const PROFILE_ROUTE = '/profile'
export const APARTMENT_ROUTE = '/apartment'